# Site settings
title: Tizen Docs
environment: production
layout: default
permalink: pretty
gitOrg: samsung-test
gitRepo: samsung-test.github.io
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .sass-cache
defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"
sass:
    sass_dir: _scss
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: test-samsung

url: "https://samsung-test.github.io/" # the base hostname & protocol for your site
