# Site settings
title: Tizen Docs
environment: production
layout: default
permalink: pretty
gitOrg: samsung-test
gitRepo: samsung-test.github.io
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .sass-cache
defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"
sass:
    sass_dir: _scss
