# Site settings
title: Tizen Docs
environment: production
layout: default
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .sass-cache

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"

sass:
    sass_dir: css
    