# Site settings
title: Tizen Docs
environment: production
permalink: pretty
markdown: kramdown
highlighter: pygments
gitOrg: samsung-test
gitRepo: samsung-test.github.io
docsVersion: docs
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .sass-cache

sass:
  sass_dir: _scss
  style: scompressed