# Site settings
title: Tizen Docs
environment: production
layout: default
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .sass-cache
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
sass:
    sass_dir: css
 
