# Site settings
title: Docs Test
environment: production
permalink: /:title
markdown: kramdown
highlighter: pygments
exclude:
- .gitignore
- README.md
- Gemfile
- Gemfile.lock

sass:
    sass_dir: css
 
