# Site settings
title: Docs Test
environment: production
permalink: pretty
markdown: kramdown
highlighter: pygments
docsVersion: docs
theme: jekyll-theme-cayman
exclude:
- .gitignore
- README.md
- Gemfile
- Gemfile.lock

sass:
    sass_dir: css
 
