version: 2
jobs:
  version-prod:
    working_directory: /project/workspace/
    docker:
      - image: ihiddenguy/docker-jekyll
    steps:
    
      # Checkout
      - checkout
          
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT

      # Generate Version site
      - type: shell
        name: Download code
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME
          echo "docsVersion: '"$CIRCLE_BRANCH"'" >> _config.yml
          bundle exec jekyll build
          ls
          rm -rf ../output
          mkdir ../output
          cp -r _site/* ../output
          git checkout _config.yml
          git checkout master
          rm -rf $CIRCLE_BRANCH
          cp -r ../output $CIRCLE_BRANCH/
          rm -rf _site/
          git add -A
          git commit -m "update"
          git push origin master

workflows:
  version: 2
  version-build-deploy:
    jobs:
      - version-prod:
          filters:
            branches:
              ignore:
                - master
                - toc
