version: 2
jobs:
  version-prod:
    working_directory: /project/workspace/
    docker:
      - image: ihiddenguy/docker-jekyll
    steps:
    
      # Checkout
      - checkout
          
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT
            
      # Download code from staging
      - type: shell
        name: Download code from staging
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME
          bundle exec jekyll build
          mkdir ../output
          cp -r _site/* ../output
          git checkout _config.yml
          git checkout master
          rm -rf css/
          rm -rf js/
          rm -rf fonts/
          rm -rf images/
          rm -rf vendor/
          if [ -f index.html ]; then
           rm index.html
          fi
          cp -rf ../output/* ./
          git add -A
          git commit -m "update"
          git push origin master
           
          
workflows:
  version: 2
  version-build-deploy:
    jobs:
      - version-prod:
          filters:
            branches:
              only:
                - toc
 
 

