version: 2
jobs:
  version-prod:
    working_directory: /project/workspace/
    docker:
      - image: ihiddenguy/docker-jekyll
    steps:
    
      # Checkout
      - checkout
          
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT
            
      # Generate Site
      - type: shell
        name: Generate Site
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME
          echo "docsVersion: 'latest'" >> _config.yml
          bundle exec jekyll build
          mkdir ../output
          cp -r _site/* ../output
          git checkout _config.yml
          git checkout master
          rm -rf css/
          rm -rf js/
          rm -rf fonts/
          rm -rf images/
          rm -rf vendor/
          rm -rf _site/

          if [ -f index.html ]; then
           rm index.html
          fi
          cp -rf ../output/* ./

          if [ -f latest ]; then
           rm latest
          fi
          LATEST_VERSION=$(<js/latest-version.txt)
          echo $LATEST_VERSION
          ln -s '/'$LATEST_VERSION'/' latest

          if [ -z "$(git status --untracked-files=no --porcelain)" ]; then 
           echo "Nothing to commit"
          else 
           git add -A
           git commit -m "update"
           git push origin master
          fi

workflows:
  version: 2
  version-build-deploy:
    jobs:
      - version-prod:
          filters:
            branches:
              only:
                - toc
