version: 2
jobs:
  version-prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/docker-ubuntu-ruby-python-npm:2.0
    steps:
    
      # Checkout
      - checkout
          
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT
            
      # Download code from staging
      - type: shell
        name: Download code from staging
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME
          bundle exec jekyll build
          cp -r _site ../output
          git checkout _config.yml
          git checkout master
          rm -rf css/
          rm -rf js/
          if [ -f index.html ]; then
           rm index.html
          fi
          cp -r ../output ./
          git add -A
          git commit -m "update"
          git push origin master
           
          
workflows:
  version: 2
  version-build-deploy:
    jobs:
      - version-prod:
          filters:
            branches:
              only:
                - toc
 

